version: '3.9'

services:
  db:
    image: postgres:15
    ports:
      - '5432'
    volumes:
      - './postgres:/var/lib/postgresql/data/'
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "cv"
    restart: always

  app:
    build: .
    ports:
      - "8000"
    depends_on:
      - db
    command: >
      bash -c '
        npx prisma db push
        npx prisma generate
        npm start
      '

  pgadmin:
    container_name: pgadmin
    depends_on:
      - db
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: info@proglib.io
      PGADMIN_DEFAULT_PASSWORD: qwertyuiop
    expose:
      - '80'
    restart: always

  nginx:
    container_name: proxy_nginx
    depends_on:
      - app
      - db
      - pgadmin
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx:/etc/nginx/conf.d
    restart: always