version: '3'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=cv
    volumes:
      - ./postgres:/var/lib/postgresql/data
    expose:
      - '5433:5433'
    restart: always

  nginx:
    container_name: proxy_nginx
    depends_on:
      - app
      - postgres
      - pgadmin
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx:/etc/nginx/conf.d
    restart: always

  pgadmin:
    container_name: pgadmin
    depends_on:
      - postgres
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: info@proglib.io
      PGADMIN_DEFAULT_PASSWORD: qwertyuiop
    expose:
      - '80'
    restart: always

  app:
    build:
      context: ./app
    tty: true
    working_dir: /opt/server
    volumes:
      - ./app:/opt/server
    env_file:
      - .env
    expose:
      - '8000'
    depends_on:
      - postgres
    command: npm run start